# Generated by Django 3.2.4 on 2022-01-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Store_name',
            field=models.CharField(default='Store name', max_length=30),
        ),
    ]
