# Generated by Django 3.2.9 on 2021-11-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('your_phone', models.IntegerField()),
                ('your_email', models.EmailField(max_length=30)),
                ('your_schedule', models.DateField()),
                ('your_message', models.TextField(max_length=250)),
                ('your_date', models.DateField()),
                ('your_address', models.TextField(max_length=100)),
            ],
        ),
    ]
